name: signal-cli CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
  workflow_call:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-graalvm:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          cache: 'gradle'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Gradle
        run: ./gradlew --no-daemon nativeCompile
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: signal-cli-native
          path: build/native/nativeCompile/signal-cli
